services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="mmornati/mock-rpmbuilder"
    - if [ -n "$TRAVIS_TAG" ]; then
      image="$image:$TRAVIS_TAG";
      fi
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --name mocktest "$image" /usr/sbin/mock --version
script:
    - official-images/test/run.sh "$image"

after_script:
    - docker images
    - docker rm mocktest

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$image";
    fi
